### ISSUE TITLE
Exception: zeroconf._exceptions.BadTypeInNameException: Type '_http._tcp.' must end with '.local.'

### ISSUE THREAD

**Issue by schaubl** [nuvlabox/peripheral-manager-network#5]
```python
Traceback (most recent call last):
  File "/opt/nuvlabox/manager.py", line 481, in <module>
    current_devices = network_manager(zeroconf, zeroconf_listener, wsdaemon)
  File "/opt/nuvlabox/manager.py", line 358, in network_manager
    zeroconf_output = parse_zeroconf_devices(zc_obj, zc_listener)
  File "/opt/nuvlabox/manager.py", line 341, in parse_zeroconf_devices
    listener.listening_to[new] = ServiceBrowser(zc, new, listener)
  File "/usr/local/lib/python3.9/site-packages/zeroconf/_services/browser.py", line 513, in __init__
    super().__init__(zc, type_, handlers, listener, addr, port, delay, question_type)
  File "/usr/local/lib/python3.9/site-packages/zeroconf/_services/browser.py", line 287, in __init__
    service_type_name(check_type_, strict=False)
  File "/usr/local/lib/python3.9/site-packages/zeroconf/_utils/name.py", line 95, in service_type_name
    raise BadTypeInNameException("Type '%s' must end with '%s'" % (type_, _LOCAL_TRAILER))
zeroconf._exceptions.BadTypeInNameException: Type '_http._tcp.' must end with '.local.'
```

**Comment by schaubl** [comment]
Fixed in a99e5fd1391e10de16fc4b449537064524c56b10
